name=input("First name:")
lname=input("Last name:")
grade=input("Grade(9-12):")
std_id=int(input("Studend ID:"))
login=input("Login:")
GPA=float(input("GPA (0.0-0.4):"))
print("\n")
print("Your Information")
# print("{:<5}First name  :{:<5}{}".format('','',name))
# print("{:<5}Last name   :{:<5}{}".format('','',lname))
# print("{:<5}Grade(9-12) :{:<5}{}".format('','',grade))
# print("{:<5}Student ID  :{:<5}{}".format('','',std_id))
# print("{:<5}Login       :{:<5}{}".format('','',login))
# print("{:<5}GPA(0.0-0.4):{:<5}{}".format('','',GPA))
print("\t Login\t:\t{}\n\t ID\t:\t{}\n\t Name\t:\t{}\n\t GPA\t:\t{}\n\t Grade\t:\t{}".format(login,std_id,name,GPA,grade))
